[features]
seeds = false
skip-lint = false


[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
cpi-example = "4JTNRRQpgLusbEhGnzTuE9kgPgMLXQX1wqBzU52GduqH"
[programs.devnet]
cpi-example = "4JTNRRQpgLusbEhGnzTuE9kgPgMLXQX1wqBzU52GduqH"


[registry]
url = "https://api.apr.dev"

[toolchain]
anchor_version = "0.31.0"
solana_version = "2.1.0"

[scripts]
test = "pnpm test "

[test]
startup_wait = 90000

[test.validator]
url = "https://api.devnet.solana.com"

[[test.validator.clone]]
address = "Eo7WjKq67rjJQSZxS6z3YkapzY3eMj6Xy8X5EQVn5UaB"    # dynamic_amm
[[test.validator.clone]]
address = "24Uqj9JCLxUeoC3hGfh5W3s9FM9uCHDS2SG3LYwBpyTi"    # dynamic_vault

[[test.validator.clone]]
address = "LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo"     # dlmm

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"     # metaplex
